### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by dulanov** [nem-toolchain/nem-toolchain#57]
- [x] No-digit flag for vanity address search (#59)
- [x] Multiple prefixes for vanity address search (#60)
- [x] Calculate hash-rate and estimated calculation times (#51)
- [x] User specified number for generated accounts (#61)
