### ISSUE TITLE
Release 0.3

### ISSUE THREAD

**Issue by dulanov** [nem-toolchain/nem-toolchain#73]
## Improvements
* [x] Exclude characters from vanity address search (#113)
* [x] Relax requirements for vanity address prefix (#112)
* [x] Option to specify the number of vanity account search workers (#136)
* [x] Option for stripping generated account to private key only (#137)
